# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'TLReactNativeApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TLReactNativeApp

  react_native_path = '../node_modules/react-native'

  pod "yoga", :path => react_native_path + '/ReactCommon/yoga'
  pod 'Folly', :podspec => react_native_path + '/third-party-podspecs/Folly.podspec'
  pod 'React', :path => react_native_path, :subspecs =>[
   'Core',
   'ART',
   'CxxBridge',
   'RCTActionSheet',
   'RCTGeolocation',
   'RCTImage',
   'RCTAnimation’,
   'RCTNetwork',
   'RCTPushNotification',
   'RCTSettings',
   'RCTText',
   'RCTVibration',
   'RCTWebSocket',
   'RCTLinkingIOS',
   'RCTCameraRoll',
   'DevSupport'
  ]

end